charts/urls.py
from django.urls import path
from . import views

app_name = 'chart'

urlpatterns = [
    path('', views.songs, name='songs'),
    path('<int:pk>/', views.detail, name='detail'),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

discussions/urls.py
from django.urls import path
from . import views

app_name = 'discussions'

urlpatterns = [
    path('', views.index, name='index'),
    path('topic-posts/<int:topic_pk>/', views.topic_posts, name='topic_posts'),
    path('user-posts/', views.user_posts, name='user_posts'),
    path('new-discussion-post/<int:topic_pk>/', views.new_discussion_post, name='new_discussion_post'),
    path('new/<int:chart_pk>/', views.new_topic, name='new'),
]

music_charts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('charts/', include('charts.urls')),
    path('discussions/', include('discussions.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

charts/models.py
from django.db import models


class Chart(models.Model):
    decade = models.CharField(max_length=10)
    image = models.ImageField(upload_to='chart_images', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Charts'
        ordering = ['decade']
    
    def __str__(self):
        return f'{self.decade}'

class Song(models.Model):
    decade = models.ForeignKey(Chart, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=False)
    artist = models.CharField(max_length=100, null=False)
    rank = models.IntegerField(default=0)
    video_link = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f'"{self.title}" by {self.artist}'

core/models.py
from django.db import models

# Create your models here.

discussions/models.py
from django.db import models
from django.contrib.auth.models import User
from charts.models import Chart


class Topic(models.Model):
    decade = models.ForeignKey(Chart, related_name='topics', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    created_by = models.ForeignKey(User, related_name='topics', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

class Post(models.Model):
    topic = models.ForeignKey(Topic, related_name='posts', on_delete=models.CASCADE)
    content = models.TextField()
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Re-enter Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

discussions/forms.py
from django import forms
from .models import Post, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'w-full py-4 rounded-xl border px-4'
            })
        }

class TopicPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-4 rounded-xl border px-4'
            })
        }

charts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Chart, Song

def songs(request):
    query = request.GET.get('query', '')
    chart_id = request.GET.get('chart', 0)
    songs = Song.objects.all().order_by('title').values()
    charts = Chart.objects.all()

    if chart_id:
        songs = songs.filter(decade_id=chart_id)

    if query:
        songs = songs.filter(Q(title__icontains=query) | Q(artist__icontains=query))

    return render(request, 'charts/songs.html', {
        'songs': songs,
        'query': query,
        'charts': charts,
        'chart_id': int(chart_id),
    })

def detail(request, pk):
    chart = get_object_or_404(Chart, pk=pk)
    related_songs = Song.objects.filter(decade_id=chart.id).order_by('-rank').values()

    return render(request, 'charts/detail.html', {
        'chart': chart,
        'songs': related_songs,
    })

core/views.py
from django.shortcuts import render
from charts.models import Chart
from .forms import SignUpForm


def index(request):
    charts = Chart.objects.all()

    return render(request, 'core/index.html', {
        'charts': charts,
    })

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'core/signup_success.html')
        else:
            form = SignUpForm()

    form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

discussions/views.py
from django.shortcuts import render, get_object_or_404, redirect
from charts.models import Chart
from .models import Post, Topic
from charts.models import Chart
from .forms import TopicForm, TopicPostForm
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    topics = Topic.objects.all()
    charts = Chart.objects.all()

    return render(request, 'discussions/index.html', {
        'topics': topics,
        'charts': charts
    })


@login_required
def new_topic(request, chart_pk):
    chart = get_object_or_404(Chart, id=chart_pk)

    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.decade = chart
            topic.created_by = request.user
            topic.save()

            return redirect('discussions:index')
    else:
        form = TopicForm()

    return render(request, 'discussions/new.html', {
        'chart': chart,
        'form': form
    })

@login_required
def new_discussion_post(request, topic_pk):
    topic = get_object_or_404(Topic, id=topic_pk)
    
    if request.method == 'POST':
        form = TopicPostForm(request.POST)

        if form.is_valid():
            topic_post = form.save(commit=False)
            topic_post.topic = topic
            topic_post.created_by = request.user
            topic_post.save()

            return redirect('discussions:index')
        
    else:
        form = TopicPostForm()
    
    return render(request, 'discussions/new_post.html', {
        'form': form
    })
    
@login_required
def user_posts(request):
    topics = Topic.objects.filter(created_by=request.user).order_by('-created_at')
    charts = Chart.objects.all()
    posts = Post.objects.filter(created_by=request.user).order_by('-created_at')

    return render(request, 'discussions/user_posts.html', {
        'topics': topics,
        'charts': charts,
        'posts': posts,
    })

@login_required
def topic_posts(request, topic_pk):
    topic = get_object_or_404(Topic, id=topic_pk)
    posts = Post.objects.filter(topic=topic)
    charts = Chart.objects.all()

    return render(request, 'discussions/topic_posts.html', {
        'topic': topic,
        'posts': posts,
        'charts': charts,
    })

charts/templates/charts/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf">
        <meta name='viewport' content='width = device-width, initial-scale = 1.0'>

        <script src='https://cdn.tailwindcss.com'></script>
        <title>{% block title %}{% endblock %} | Top Music Charts</title>
    </head>
    <body>
        <nav class='py-6 px-6 flex justify-between items-center border-b border-gray-300'>
            <a href='/' class='text-2xl font-semibold'>Top Charts by Decade</a>

            <div class='space-x-6'>
                <a href='#' class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Sign up</a>
                <a href='#'
                    class='px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700'>Login</a>
            </div>
        </nav>
        <div class='px-6 py-6'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
    <footer class='py-6 px-6 flex justify-between bg-gray-600'>
        <div class='w-2/3 pr-10'>
            <h3 class='mb-5 font-semibold text-gray-200'>About Us</h3>

            <p class='text-lg text-gray-400'>Have you ever been curious about the greatest and most popular songs of the decade in the 1950's? Or maybe the 70's? Or even during your childhood in the 90's or 2000's? This is the site to find out EXACTLY that!</p>
        </div>
        <div class='w-1/3'>
            <h3 class='mb-5 font-semibold text-gray-200'>Menu</h3>

            <ul class='space-y-2'>
                <li><a href='#' class='text-lg text-gray-400 hover:text-white hover:underline'>About</a></li>
                <li><a href='#'
                        class='text-lg text-gray-400 hover:text-white hover:underline'>Contact</a></li>
                <li><a href='#' class='text-lg text-gray-400 hover:text-white hover:underline'>Privacy</a></li>
                <li><a href='#' class='text-lg text-gray-400 hover:text-white hover:underline'>Terms of use</a></li>
            </ul>
        </div>
    </footer>
</html>

charts/templates/charts/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ chart.decade }}{% endblock %}

{% block content %}
<div class='bg-purple-50 rounded-xl border-2 border-gray-500 px-10'>
    <h1 class='text-8xl px-2 py-3 text-center mb-6'>{{ chart.decade }}</h1>
        <div class='flex justify-between'>
            <p class='inline-block text-4xl px-2 py-3 text-gray-800 text-left'>Top 10 Songs of the Decade</p>
            <a href='{% url 'discussions:new' chart.id %}' class='inline-block mb-6 text-center px-6 py-3 text-lg font-semibold bg-purple-500 text-white rounded-xl hover:bg-purple-700'>New Discussion Topic</a>
        </div>
        <p class='text-2xl px-2 pb-6 text-gray-500'>According to Billboards</p>
    <div class='text-white'>
        {% for song in songs %}
        <div class='grid grid-rows-5 gap-1 px-2 py-2'>
            <div class='py-4 text-center bg-gray-400 row-span-1 rounded-full border-2 border-black'>
                <h2 class='text-6xl text-purple-600'><strong>#{{ song.rank }}. </strong></h2>
                <p class='text-2xl'>"{{ song.title }}" by {{ song.artist }}</p>
            </div>
            <div class='flex flex-row justify-center items-center row-span-4'>
                <iframe width='560' height='315' src='{{ song.video_link }}' title='YouTube video player' frameborder='0'
                    allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share'
                    allowfullscreen></iframe>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

charts/templates/charts/index.html
{% extends 'charts/base.html' %}

{% block title %}Charts{% endblock %}

{% block content %}
    <h1 class='text-center text-6xl'>Decades</h1>
        {% for chart in charts %}
            <div>
                <a href = '{% url 'chart:detail' chart.id %}'>
                    <div>
                        <div class = 'p-6 bg-white rounded-b-xl'>
                            <h2 class = 'text-2xl hover:text-4xl'>{{ chart.decade }}</h2>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
{% endblock %}

charts/templates/charts/songs.html
{% extends 'core/base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    <div class='pb-6 grid-col-4 gap-4 bg-gray-200'>
        <div class='col-span-1 text-center text-2xl py-3'>
            <form method='get' action='{% url 'chart:songs' %}' class='col-span-1'>
                <input name='query' class='w-3/4 py-4 px-6 border rounded-xl' type='text' value='{{ query }}' placeholder='Find a Song!'>
                <button class='mt-2 py-4 px-8 text-lg bg-purple-500 text-white rounded-xl'>Search</button>
                <a href='{% url 'chart:songs' %}' class='mt-2 py-4 px-8 inline-block bg-red-500 text-lg rounded-xl text-white'>Clear</a>
            </form>

            <div class='grid-col-4 gap-2'>
                <nav class='py-6 px-6 flex justify-between items-center border-b border-gray-300'>
                    {% for chart in charts %}
                        <div class='row-span-1 py-2 px-2 rounded-xl{% if chart.id == chart_id %} bg-gray-300{% endif %}'>
                            <a href='{% url 'chart:songs' %}?query={{ query }}&chart={{ chart.id }}'>{{ chart.decade }}</a>
                        </div>
                    {% endfor %}
                    </nav>
            </div>
        </div>

        <div class='row-span-1 px-3'>
            <p class='text-gray-500 text-lg'>Examples:</p>
            {% for song in songs%}
            <div>
                    <div class='px-3 py-1 bg-purple-500 rounded-b-xl my-2'>
                        <div class = 'p-6 py-2 bg-purple-300 rounded-b-lg'>
                            <a href='{% url 'chart:detail' song.decade_id %}' class = 'font-serif text-xl hover:text-2xl hover:text-white'>"{{ song.title }}" by {{ song.artist }}</h2>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf">
        <meta name='viewport' content='width = device-width, initial-scale = 1.0'>

        <script src='https://cdn.tailwindcss.com'></script>
        <title>{% block title %}{% endblock %} | Top Music Charts</title>
    </head>
    <body>
        <nav class='py-6 px-6 flex justify-between items-center border-b border-gray-300'>
            <a href='/' class='text-4xl font-semibold'>BILLBOARDS Top Ten by Decade</a>

            <div class='grid grid-cols-4 gap-4 items-center'>
                <a href='{% url 'chart:songs' %}' class='text-xl font-semibold hover:text-gray-500'>Search Songs</a>
                <a href='{% url 'core:logout' %}'
                    class='px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700'>Logout</a>
                {% if request.user.is_authenticated %}
                <a href='{% url 'discussions:index' %}' class='px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700'>Discussions</a>
                <a href='{% url 'discussions:user_posts' %}' class='px-6 py-3 text-lg font-semibold bg-yellow-500 text-white rounded-xl hover:bg-yellow-700'>My Posts</a>
                {% else %}
                <a href='{% url 'core:signup' %}' class='px-6 py-3 text-lg font-semibold bg-pink-500 text-white rounded-xl hover:bg-pink-700'>Sign up</a>
                <a href='{% url 'core:login' %}'
                    class='px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700'>Login</a>    
                {% endif %}
            </div>
        </nav>
        <div class='px-6 py-6'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
    <footer class='py-6 px-6 flex justify-between bg-gray-600'>
        <div class='w-2/3 pr-10'>
            <h3 class='mb-5 font-semibold text-gray-200'>About Us</h3>

            <p class='text-lg text-gray-400'>Have you ever been curious about the greatest and most popular songs of the decade in the 1950's? Or maybe the 70's? Or even during your childhood in the 90's or 2000's? This is the site to find out EXACTLY that!</p>
        </div>
        <div class='w-1/3'>
            <h3 class='mb-5 font-semibold text-gray-200'>Menu</h3>

            <ul class='space-y-2'>
                <li><a href='#' class='text-lg text-gray-400 hover:text-white hover:underline'>About</a></li>
                <li><a href='#'
                        class='text-lg text-gray-400 hover:text-white hover:underline'>Contact</a></li>
                <li><a href='#' class='text-lg text-gray-400 hover:text-white hover:underline'>Privacy</a></li>
                <li><a href='#' class='text-lg text-gray-400 hover:text-white hover:underline'>Terms of use</a></li>
            </ul>
        </div>
    </footer>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Charts{% endblock %}

{% block content %}
    <h1 class='text-center text-6xl py-10 italic'>Choose a Decade!</h1>
        <div class='grid grid-cols-3 gap-4 items-center'>
        {% for chart in charts %}
            <div>
                <a href = '{% url 'chart:detail' chart.id %}'>
                    <div class='px-3 py-3'>
                        <div>
                            <img src='{{ chart.image.url }}' class='rounded-t-xl border-2 border-black'>
                        </div>
                        <div class = 'p-6 bg-white rounded-b-xl border-r-2 border-l-2 border-b-2 border-black'>
                            <h2 class = 'text-2xl text-center hover:text-4xl'>{{ chart.decade }}</h2>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

    <div class='w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6'>
        <h1 class='mb-6 text-3xl'>Login</h1>
        
        <form method='post' action='.'>
            {% csrf_token %}

            <div class='mb-3'>
                <label class='inline-block mb-2'>Username</label><br>
                {{ form.username }}
            </div>
            <div class='mb-3'>
                <label class='inline-block mb-2'>Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class='mb-3 p-6 bg-red-100 rounded-xl'>
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class='py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white'>Submit</button>
        </form>
    </div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

    <div class='w-1/2 my-6 mx-auto bg-gray-100 rounded-xl p-6'>
        <h1 class='mb-6 text-3xl'>Sign Up</h1>
        
        <form method='post' action='.'>
            {% csrf_token %}

            <div class='mb-3'>
                <label class='inline-block mb-2'>Username</label><br>
                {{ form.username }}
            </div>
            <div class='mb-3'>
                <label class='inline-block mb-2'>E-mail Address</label><br>
                {{ form.email }}
            </div>
            <div class='mb-3'>
                <label class='inline-block mb-2'>Password</label><br>
                {{ form.password1 }}
            </div>
            <div class='mb-3'>
                <label class='inline-block mb-2'>Confirm Password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class='mb-3 p-6 bg-red-100 rounded-xl'>
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class='py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white'>Submit</button>
        </form>
    </div>

{% endblock %}

core/templates/core/signup_success.html
{% extends 'core/base.html' %}

{% block title %}Welcome!{% endblock %}

{% block content %}
    <div class='w-1/2 text-lg'>
        <h1>You Have successfully signed up, <strong>Welcome!</strong></h1>
        <h2>You may click <a href='{% url 'core:index' %}' class='txt-xl text-teal-500'>HERE</a> to return to the home page.</h2>
    </div>
{% endblock %}

discussions/templates/discussions/index.html
{% extends 'core/base.html' %}

{% block title %}Discussions{% endblock %}

{% block content %}
    <h1 class='mb-6 text-3xl'>Discussions</h1>
    
    <div class='space-x-6'>
        {% for topic in topics %}
            <a href='{% url 'discussions:topic_posts' topic.id %}'>
                <div class='p-6 flex bg-gray-100 rounded-xl'>
                    <div class='pr-6 border-r-2 border-gray-300'>
                        <img src='{{ topic.decade.image.url }}' class='w-20 rounded-xl py-3'>
                        <p class='px-4'>{{ topic.decade }}</p>
                    </div>
                    <div class='px-6'>
                        <a href='{% url 'discussions:topic_posts' topic.id %}' class='mb-6'><strong>{{ topic.created_by }}</strong> | Last Modified: {{ topic.updated_at }} | Created: {{ topic.created_at }}</a>
                        <p class='text-2xl'>{{ topic.name }}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

discussions/templates/discussions/new.html
{% extends 'core/base.html' %}
{% block title %}New Topic{% endblock %}

{% block content %}
    <h1 class='mb-6 text-3xl'>New Topic</h1>

    <form method='post' action='.'>
        {% csrf_token %}

        <div class='space-y-4'>
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 px-6 bg-red-100 rounded-xl'>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {{% endif %}

        <button class='mt-6 py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700'>Post</button>
    </form>
{% endblock %}

discussions/templates/discussions/new_post.html
{% extends 'core/base.html' %}
{% block title %}New Post{% endblock %}

{% block content %}
    <h1 class='mb-6 text-3xl'>Post to Discussion Board:</h1>

    <form method='post' action='.'>
        {% csrf_token %}

        <div class='space-y-4'>
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 p-6 bg-red-100 rounded-xl'>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {{% endif %}

        <button class='mt-6 py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700'>Post</button>
    </form>
{% endblock %}

discussions/templates/discussions/topic_posts.html
{% extends 'core/base.html' %}
{% block title %}Be Kind!{% endblock %}

{% block content %}
    <h1 class='mb-6 text-3xl'>Discussions</h1>
    
    <div class='my-4 px-2 py-6 flex bg-purple-100 rounded-xl w-1/2'>
        <header class='py-4 px-4 text-xl text-center text-green-800'>Discussion Topic</header>
        <div class='px-6'>
            <p class='mb-6'><strong>{{ topic.created_by }}</strong><br>Last Modified: {{ topic.updated_at }} | Created: {{ topic.created_at }}</a>
            <p class='text-2xl text-center'>{{ topic.name }}</p>
        </div>
    </div>

    <div class='my-4 px-6 py-6 flex bg-gray-100 rounded-xl'></div>
    {% for post in posts %}
            <div class='my-4 px-6 py-6 flex bg-gray-100 rounded-xl'>
                <p class='mb-6'><strong>{{ post.created_by }}</strong> | {{ post.created_at }}</p>
                <p class='text-xl'>{{ post.content }}</p>
            </div>
    {% endfor %}
    </div>
    
    <div>
        <h2 class='mb-6 text-3xl'>Want to Add to this Discussion?</h2>
        <a href='{% url 'discussions:new_discussion_post' topic.id %}' class='mt-6 py-4 px-8 text-lg rounded-xl bg-teal-500 hover:bg-teal-700'>Click Here!</a>
    </div>
{% endblock %}

discussions/templates/discussions/user_posts.html
{% extends 'core/base.html' %}

{% block title %}My Posts{% endblock %}

{% block content %}
    <h1 class='mb-6 text-3xl'>My Discussion Posts:</h1>

    <div class='grid grid-cols-2 gap-4'>
        <div class='col-span-1 bg-gray-200 p-3 rounded-xl'>
        <header class='py-4 px-4 text-xl text-center text-green-800'>Topic Discussions I Started</header>
            {% for topic in topics %}
                    <div class='px-3 flex bg-purple-100 rounded-xl col-span-1 items-center border-black border-2'>
                        <div class='pr-6 border-r-2 border-gray-300'>
                            <img src='{{ topic.decade.image.url }}' class='w-20 rounded-xl py-3'>
                            <a href='{% url 'discussions:topic_posts' topic.id %}' class='px-4'>{{ topic.decade }}</a>
                        </div>
                        
                        <div class='px-6'>
                            <a href='{% url 'discussions:topic_posts' topic.id %}' class='mb-6'><strong>{{ topic.created_by }}</strong> | {{ topic.created_at }}</a>
                            <p class='text-2xl'>{{ topic.name }}</p>
                        </div>
                    </div>
            {% endfor %}
        </div>

        <div class='px-3 col-span-1 bg-gray-200 p-3 rounded-xl'>
        <header class='py-4 px-4 text-xl text-center text-green-800'>Posts I've Made</header>
            {% for post in posts %}
                <div class='px-3 flex bg-teal-100 rounded-xl col-span-1 items-center border-black border-2'>
                    {% for topic in topics %}
                        <img src='{{ topic.decade.image.url }}' class='w-20 rounded-xl py-3 px-1'>
                        <a href='{% url 'discussions:topic_posts' topic.id %}' class='mb-6 px-2'><strong>{{ post.created_by }}</strong> | {{ post.created_at }}</a>
                    {% endfor %}
                    <p class='text-xl mt-4 p-6'>{{ post.content }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}